### PR TITLE
Emoji v2, now with no words!

### PR DESCRIPTION
**Pull request by pixelyunicorn**

### CODE REVIEW

**Comment by pixelyunicorn** [comment]
(Also worth noting: I renamed en_emoji to just emoji because it's a universal language)

**Comment by tjhorner** [comment]
image
ok sure lol

**Comment by tjhorner** [comment]
just noticed a _**MAJOR**_ flaw after merging: the open graph metadata isn't emojified. pls fix

**Comment by tylermenezes** [comment]
@pixelyunicorn this is basically a breaking change untli the open graph metadata is fixed

**Comment by pixelyunicorn** [comment]
Hey, it’s not a breaking change until we host a CodeDay in the quiet city of ‘Emoji’!

**Pull request merged**
